# config/secrets.yml
development:
  secret_key_base: 12345... # secret for the development environment

test:
  secret_key_base: 67890... # secret for the test environment

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> # secret for the production environment, usually set via ENV
